version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_NAME=ODIADEV Voice
      - ADMIN_TOKEN=your-super-secret-admin-token-here
      - KEY_PEPPER=your-super-secret-key-pepper-here
      - ODIA_UPSTREAM_BASE=http://13.244.179.175
      - ODIA_UPSTREAM_KEY=your-upstream-service-api-key-here
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: